### ISSUE TITLE
Is that conflict with ”erlang:binary_to_existing_atom/1“?

### ISSUE THREAD

**Issue by wwhai** [Bluehouse-Technology/grpc#17]
```
binary_to_existing_atom(B) ->
    list_to_existing_atom(binary_to_list(B)).

```
Is that conflict with ”erlang:binary_to_existing_atom/1“? ==> https://erlang.org/doc/man/erlang.html#binary_to_existing_atom-1

**Comment by cmullaparthi** [comment]
Yes, it does clash. It is fixed now.
